import type { Metadata } from "next"
import Link from "next/link"
import { ArrowRight } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { BlogExplorer } from "@/components/blog-explorer"
import { NewsletterForm } from "@/components/forms"
import { PageHero, SectionHeading } from "@/components/page-sections"
import { posts } from "@/lib/site-data"
export const metadata:Metadata={title:"Insights",description:"Field notes from Wolfitpark on AI, software products, cloud, connected operations, and digital transformation.",alternates:{canonical:"/blog"}}
export default function BlogPage(){const featured=posts[0];return <><PageHero eyebrow="Wolfitpark insights" title="Practical thinking for people building what is next." description="Perspectives on software, AI, cloud, products, and the operating decisions behind meaningful transformation."/><section className="section-pad"><div className="container-site"><article className="grid overflow-hidden rounded-3xl border border-border bg-card lg:grid-cols-2"><div className="relative min-h-80 bg-foreground p-8 text-background"><div className="hero-grid absolute inset-0 opacity-20"/><div className="relative"><Badge>Featured perspective</Badge><p className="mt-24 text-xs uppercase tracking-widest text-primary">{featured.category}</p><p className="mt-3 text-4xl font-semibold leading-tight">Trusted AI starts with a better operating model.</p></div></div><div className="flex flex-col justify-center p-8 lg:p-12"><p className="text-sm text-muted-foreground">{featured.date} · {featured.read}</p><h2 className="mt-5 text-3xl font-semibold">{featured.title}</h2><p className="mt-5 leading-relaxed text-muted-foreground">{featured.excerpt}</p><Button className="mt-7 w-fit" render={<Link href={`/blog/${featured.slug}`}/>}>Read featured article<ArrowRight data-icon="inline-end"/></Button></div></article></div></section><section className="pb-24"><div className="container-site"><SectionHeading eyebrow="Latest thinking" title="Ideas you can put to work."/><div className="mt-10"><BlogExplorer/></div></div></section><section className="section-pad bg-foreground text-background"><div className="container-site grid gap-8 lg:grid-cols-2 lg:items-center"><div><h2 className="text-3xl font-semibold">One useful note each month.</h2><p className="mt-3 text-background/60">No noise. Just practical perspective from teams designing and building modern systems.</p></div><NewsletterForm compact/></div></section></>}
