import Link from "next/link"
import type { LucideIcon } from "lucide-react"
import { ArrowRight, Check, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

export function Eyebrow({ children, className }: { children: React.ReactNode; className?: string }) { return <p className={cn("mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary", className)}><Sparkles className="size-3.5"/>{children}</p> }
export function SectionHeading({ eyebrow, title, description, align="left", className }: { eyebrow?: string; title: string; description?: string; align?: "left"|"center"; className?: string }) { return <div className={cn("max-w-2xl",align==="center"&&"mx-auto text-center",className)}>{eyebrow&&<Eyebrow className={cn(align==="center"&&"justify-center")}>{eyebrow}</Eyebrow>}<h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">{title}</h2>{description&&<p className="mt-5 text-pretty text-base leading-relaxed text-muted-foreground sm:text-lg">{description}</p>}</div> }
export function PageHero({ eyebrow, title, description, actions, children }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode; children?: React.ReactNode }) { return <section className="relative overflow-hidden border-b border-border bg-muted/30"><div className="hero-grid absolute inset-0 opacity-45"/><div className="container-site relative py-20 sm:py-28"><div className="max-w-4xl"><Eyebrow>{eyebrow}</Eyebrow><h1 className="text-balance text-4xl font-semibold tracking-[-.04em] sm:text-6xl lg:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground sm:text-xl">{description}</p>{actions&&<div className="mt-8 flex flex-wrap gap-3">{actions}</div>}</div>{children}</div></section> }
export function IconCard({ title, description, icon: Icon, href, className }: { title:string; description:string; icon:LucideIcon; href?:string; className?:string }) { const content=<><div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{description}</p>{href&&<span className="mt-6 inline-flex items-center gap-1 text-sm font-medium text-primary">Learn more <ArrowRight className="size-4"/></span>}</>; return href?<Link href={href} className={cn("group rounded-2xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl hover:shadow-primary/5",className)}>{content}</Link>:<article className={cn("rounded-2xl border border-border bg-card p-6",className)}>{content}</article> }
export function FeatureList({ items }: { items: readonly string[] }) { return <ul className="flex flex-col gap-2.5">{items.map(item=><li key={item} className="flex items-start gap-2 text-sm text-muted-foreground"><span className="mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"><Check className="size-3"/></span>{item}</li>)}</ul> }
export function CtaSection({ title="Ready to build what your business needs next?", description="Bring us the complexity. We will help you turn it into a clear, scalable system.", primary="Book consultation", href="/consultation" }: { title?:string; description?:string; primary?:string; href?:string }) { return <section className="section-pad"><div className="container-site"><div className="relative overflow-hidden rounded-3xl bg-primary p-8 text-primary-foreground sm:p-12 lg:flex lg:items-center lg:justify-between lg:p-16"><div className="hero-grid absolute inset-0 opacity-20"/><div className="relative max-w-2xl"><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h2><p className="mt-4 text-pretty leading-relaxed text-primary-foreground/75">{description}</p></div><Button variant="secondary" size="lg" className="relative mt-8 lg:mt-0" render={<Link href={href}/>} nativeButton={false}>{primary}<ArrowRight data-icon="inline-end"/></Button></div></div></section> }
