"use client"
import { useState } from "react"
import { ArrowUpRight, Quote } from "lucide-react"
import { projects } from "@/lib/site-data"
import { Badge } from "@/components/ui/badge"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"

const filters=["All","SaaS","Healthcare","Finance","Retail","Enterprise","AI"]
export function PortfolioGallery(){const[filter,setFilter]=useState("All");const shown=filter==="All"?projects:projects.filter(p=>p.category===filter);return <><ToggleGroup value={[filter]} onValueChange={v=>setFilter(v[0]??"All")} className="mb-10 flex flex-wrap justify-start" aria-label="Filter projects">{filters.map(f=><ToggleGroupItem key={f} value={f}>{f}</ToggleGroupItem>)}</ToggleGroup><div className="grid gap-6 lg:grid-cols-2">{shown.map((project,i)=><article key={project.slug} className="group overflow-hidden rounded-3xl border border-border bg-card"><div className="relative min-h-64 overflow-hidden bg-muted p-6"><div className="hero-grid absolute inset-0 opacity-50"/><div className="relative h-full rounded-2xl border border-border bg-background p-4 shadow-xl transition-transform duration-500 group-hover:-translate-y-1 group-hover:scale-[1.01]"><div className="flex items-center justify-between border-b border-border pb-3"><span className="text-xs font-semibold">{project.category} platform</span><ArrowUpRight className="size-4 text-primary"/></div><div className="mt-4 grid grid-cols-3 gap-3"><div className="col-span-2 rounded-xl bg-foreground p-4 text-background"><p className="text-[10px] text-background/50">Key outcome</p><p className="mt-7 text-2xl font-semibold text-primary">{project.result}</p></div><div className="rounded-xl border border-border p-3"><div className="flex h-full items-end gap-1">{[35,70,50,88].map((h,n)=><span key={n} className="flex-1 rounded-t bg-primary" style={{height:`${h}%`,opacity:.4+n*.15}}/>)}</div></div></div><div className="mt-3 grid grid-cols-3 gap-2">{["Users","Tasks","Growth"].map((t,n)=><div key={t} className="rounded-lg border border-border p-3"><p className="text-[9px] text-muted-foreground">{t}</p><p className="mt-2 text-sm font-semibold">{["1,240","84%","+28%"][n]}</p></div>)}</div></div></div><div className="p-7"><div className="flex items-center justify-between gap-3"><Badge variant="secondary">{project.category}</Badge><span className="text-sm font-semibold text-primary">{project.result}</span></div><h2 className="mt-5 text-2xl font-semibold">{project.title}</h2><p className="mt-3 leading-relaxed text-muted-foreground">{project.summary}</p><div className="mt-5 flex flex-wrap gap-2">{project.tech.map(t=><Badge variant="outline" key={t}>{t}</Badge>)}</div><blockquote className="mt-6 flex gap-3 border-t border-border pt-5 text-sm italic text-muted-foreground"><Quote className="size-4 shrink-0 text-primary"/>“{project.quote}”</blockquote></div></article>)}</div></>}
