"use client"
import { useState } from "react"
import Link from "next/link"
import { Check, Minus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Badge } from "@/components/ui/badge"
const plans=[{name:"Starter",monthly:4500,description:"A focused foundation for a growing team with one clear product or workflow goal.",features:["Product discovery sprint","One delivery squad","Core web platform","Cloud deployment","30-day launch support"]},{name:"Professional",monthly:9500,description:"Ongoing product and automation capacity for organizations building momentum.",features:["Continuous roadmap delivery","Cross-functional senior team","Integrations and automation","Analytics and observability","Priority support"]},{name:"Enterprise",monthly:null,description:"A tailored transformation partnership for complex systems, governance, and scale.",features:["Multi-team delivery","Architecture and modernization","Security and governance","Custom service levels","Executive steering"]}]
const comparison=[["Discovery and roadmap",true,true,true],["Custom product design",true,true,true],["Dedicated delivery team",false,true,true],["AI and workflow automation",false,true,true],["Enterprise integrations",false,false,true],["Custom SLA and governance",false,false,true]] as const
export function PricingPlans(){const[annual,setAnnual]=useState(false);return <><div className="mb-10 flex items-center justify-center gap-3"><span className={!annual?"font-medium":"text-muted-foreground"}>Monthly</span><Switch checked={annual} onCheckedChange={setAnnual} aria-label="Toggle annual pricing"/><span className={annual?"font-medium":"text-muted-foreground"}>Annual</span><Badge>Save 15%</Badge></div><div className="grid gap-5 lg:grid-cols-3">{plans.map((plan,i)=><article key={plan.name} className={`relative flex flex-col rounded-3xl border p-7 ${i===1?"border-primary bg-primary text-primary-foreground shadow-xl shadow-primary/15":"border-border bg-card"}`}>{i===1&&<Badge variant="secondary" className="absolute right-5 top-5">Most popular</Badge>}<p className="text-sm font-semibold">{plan.name}</p><div className="mt-8 min-h-14">{plan.monthly?<><span className="text-4xl font-semibold tracking-tight">${Math.round(plan.monthly*(annual?.85:1)).toLocaleString()}</span><span className={i===1?"text-primary-foreground/60":"text-muted-foreground"}> / month</span></>:<span className="text-4xl font-semibold">Let&apos;s talk</span>}</div><p className={`mt-5 text-sm leading-relaxed ${i===1?"text-primary-foreground/70":"text-muted-foreground"}`}>{plan.description}</p><ul className="mt-7 flex flex-col gap-3">{plan.features.map(f=><li key={f} className="flex gap-2 text-sm"><Check className="mt-0.5 size-4 shrink-0"/>{f}</li>)}</ul><Button className="mt-8" variant={i===1?"secondary":"default"} render={<Link href="/consultation"/>}>{plan.monthly?"Start a conversation":"Contact enterprise"}</Button></article>)}</div><div className="mt-20 overflow-x-auto"><table className="w-full min-w-2xl border-collapse text-left"><caption className="mb-6 text-left text-2xl font-semibold">Compare engagement plans</caption><thead><tr className="border-b border-border"><th className="py-4 text-sm">Capability</th>{plans.map(p=><th key={p.name} className="px-4 py-4 text-center text-sm">{p.name}</th>)}</tr></thead><tbody>{comparison.map(([label,...values])=><tr key={label} className="border-b border-border"><th className="py-4 text-sm font-normal text-muted-foreground">{label}</th>{values.map((v,i)=><td key={i} className="px-4 py-4 text-center">{v?<Check className="mx-auto size-4 text-primary"/>:<Minus className="mx-auto size-4 text-muted-foreground"/>}</td>)}</tr>)}</tbody></table></div></>}
