import {
  Activity, BarChart3, Bell, Bot, Boxes, BriefcaseBusiness, Building2,
  ClipboardCheck, Cloud, CloudCog, Code2, CreditCard, Database, FileText, Globe,
  GraduationCap, HardHat, HeadphonesIcon, HeartPulse, Key, Landmark,
  LayoutDashboard, LineChart, LockKeyhole, Mail, MapPin, MessageSquare,
  Palette, PlugZap, Receipt, RefreshCcw, Rocket, Settings2, ShieldCheck,
  ShoppingBag, ShoppingCart, Smartphone, Sparkles, Star, Store, UserCheck,
  Users, Workflow, Wrench,
} from "lucide-react"

export const services = [
  ["Custom Software Development", "Purpose-built platforms engineered around your operations, users, and growth model.", Code2],
  ["Business Management Systems", "One connected operating system for projects, teams, customers, and financial workflows.", BriefcaseBusiness],
  ["CRM Solutions", "Give revenue teams a complete customer view, intelligent follow-ups, and reliable forecasting.", Users],
  ["ERP Development", "Unify planning, procurement, finance, inventory, and reporting without legacy friction.", Boxes],
  ["AI Automation", "Deploy secure AI assistants and automations that turn repetitive work into scalable systems.", Bot],
  ["Workflow Automation", "Connect tools, remove handoffs, and orchestrate approvals across every department.", Workflow],
  ["Web Development", "Fast, accessible digital experiences that convert interest into measurable business outcomes.", Code2],
  ["Mobile Applications", "Native-quality mobile products with thoughtful UX, secure data, and reliable performance.", Smartphone],
  ["API Development", "Secure, documented APIs that connect your products, partners, and operational data.", PlugZap],
  ["Cloud Infrastructure", "Resilient cloud foundations optimized for speed, governance, observability, and cost.", CloudCog],
  ["Cybersecurity", "Practical security architecture, access controls, testing, and risk reduction built into delivery.", ShieldCheck],
  ["Data Analytics", "Decision-ready dashboards and data products that make performance visible in real time.", BarChart3],
  ["UI/UX Design", "Research-led product design that makes sophisticated workflows feel clear and intuitive.", Palette],
  ["IT Consulting", "A senior technical partner for architecture, modernization, roadmaps, and delivery governance.", Settings2],
  ["Software Maintenance", "Proactive support, upgrades, monitoring, and continuous improvements after launch.", Wrench],
] as const

export const solutions = [
  ["Small Business", "Replace disconnected spreadsheets with a practical digital operating system that grows with you.", Store],
  ["Startups", "Move from concept to trusted product with lean architecture, rapid validation, and a scalable foundation.", Rocket],
  ["Healthcare", "Coordinate care operations with privacy-aware systems, secure workflows, and actionable reporting.", HeartPulse],
  ["Education", "Simplify enrollment, learning operations, communication, and institutional analytics.", GraduationCap],
  ["Finance", "Build auditable, secure workflows for customer operations, reporting, and risk management.", Landmark],
  ["Retail", "Connect customers, inventory, stores, fulfillment, and performance data in one intelligent platform.", ShoppingBag],
  ["Manufacturing", "Improve planning, traceability, quality, and shop-floor visibility across the production lifecycle.", Settings2],
  ["Construction", "Keep field teams, budgets, schedules, documents, and stakeholders aligned from bid to closeout.", HardHat],
  ["Professional Services", "Standardize delivery, utilization, client communication, and revenue operations.", BriefcaseBusiness],
  ["Government", "Modernize constituent and internal services with accessible, secure, and accountable systems.", Building2],
] as const

export const products = [
  { name: "Wolf CRM", label: "Revenue intelligence", description: "Turn every lead and customer interaction into a coordinated growth motion.", features: ["Unified pipeline", "Smart follow-ups", "Revenue forecasting"], icon: Users, metric: "+31%", metricLabel: "pipeline velocity" },
  { name: "Wolf ERP", label: "Connected operations", description: "Run finance, procurement, delivery, and resources from a single source of truth.", features: ["Financial operations", "Resource planning", "Approvals"], icon: Boxes, metric: "42h", metricLabel: "saved each month" },
  { name: "Wolf HR", label: "People operations", description: "Create a better employee experience from onboarding through performance.", features: ["Employee records", "Time and leave", "Performance cycles"], icon: BriefcaseBusiness, metric: "94%", metricLabel: "team adoption" },
  { name: "Wolf Inventory", label: "Inventory control", description: "Know what is available, what is moving, and what needs attention in real time.", features: ["Multi-location stock", "Reorder intelligence", "Supplier insights"], icon: Database, metric: "-23%", metricLabel: "stock variance" },
  { name: "Wolf POS", label: "Modern commerce", description: "Deliver fast checkout experiences connected to inventory and customer history.", features: ["Omnichannel sales", "Customer profiles", "Live reporting"], icon: Store, metric: "1.8s", metricLabel: "checkout time" },
  { name: "Wolf Analytics", label: "Decision intelligence", description: "Translate operational data into clear, trusted answers for every leader.", features: ["Executive dashboards", "Custom metrics", "Scheduled reports"], icon: LineChart, metric: "6x", metricLabel: "faster reporting" },
  { name: "Wolf AI Assistant", label: "Everyday intelligence", description: "Give teams a secure copilot that understands business context and takes action.", features: ["Knowledge search", "Task automation", "Action approvals"], icon: Sparkles, metric: "71%", metricLabel: "tasks automated" },
  { name: "Wolf Workflow", label: "Process orchestration", description: "Design, launch, and improve cross-functional workflows without bottlenecks.", features: ["Visual builder", "Smart routing", "SLA monitoring"], icon: Workflow, metric: "-39%", metricLabel: "cycle time" },
] as const

export const projects = [
  { slug: "atlas-care", title: "Atlas Care Command Center", category: "Healthcare", summary: "A coordinated patient operations platform for a multi-location care network.", tech: ["Next.js", "Postgres", "FHIR"], result: "38% faster intake", quote: "Wolfitpark made complex clinical operations feel simple." },
  { slug: "northstar-finance", title: "Northstar Risk Cloud", category: "Finance", summary: "An auditable risk workflow and analytics platform built for a growing fintech.", tech: ["React", "Python", "AWS"], result: "64% less review time", quote: "We gained control and speed without compromising governance." },
  { slug: "meridian-retail", title: "Meridian Retail OS", category: "Retail", summary: "Unified inventory, store performance, and customer intelligence across 84 locations.", tech: ["Next.js", "Node.js", "Azure"], result: "23% fewer stockouts", quote: "It changed how our entire company makes decisions." },
  { slug: "forge-ops", title: "Forge Enterprise Ops", category: "Enterprise", summary: "A secure operations hub connecting procurement, projects, vendors, and finance.", tech: ["TypeScript", "Postgres", "Kubernetes"], result: "$1.2M annual savings", quote: "A true transformation partner from discovery through launch." },
  { slug: "relay-ai", title: "Relay AI Service Desk", category: "AI", summary: "A governed AI assistant that resolves requests and coordinates human approvals.", tech: ["AI SDK", "Next.js", "Vector Search"], result: "71% auto-resolution", quote: "The assistant feels like an experienced member of our team." },
  { slug: "launchpad", title: "Launchpad SaaS Platform", category: "SaaS", summary: "A multi-tenant business platform designed to scale from first customer to enterprise.", tech: ["Next.js", "Stripe", "Neon"], result: "3.4x activation", quote: "We launched a stronger product in a fraction of the expected time." },
] as const

export const testimonials = [
  { quote: "Wolfitpark connected systems we thought would always remain fragmented. We now operate from one reliable view of the business.", name: "Elena Brooks", role: "COO, Meridian Group", rating: 5 },
  { quote: "They combined product thinking with serious engineering discipline. Every decision was tied to a real operational outcome.", name: "Marcus Chen", role: "Founder, Northstar Labs", rating: 5 },
  { quote: "The team listened deeply, moved quickly, and left us with a platform our people genuinely enjoy using.", name: "Priya Raman", role: "VP Operations, Atlas Health", rating: 5 },
]

export const faqs = [
  ["What types of software does Wolfitpark build?", "We design and engineer business platforms, SaaS products, CRM and ERP systems, AI automations, mobile apps, APIs, analytics products, and cloud infrastructure."],
  ["Do you work with startups and established enterprises?", "Yes. Our delivery model adapts to early-stage product validation, growing mid-market operations, and enterprise modernization programs."],
  ["Can you modernize an existing legacy system?", "Yes. We begin with an architecture and workflow assessment, then define an incremental modernization roadmap that protects business continuity."],
  ["How do software projects begin?", "Every engagement starts with a focused discovery phase covering goals, users, workflows, technical constraints, risks, and measurable success criteria."],
  ["How long does a typical project take?", "Focused product releases can take several weeks, while larger platforms are usually delivered in phased releases over several months."],
  ["Do you offer fixed-price engagements?", "We offer milestone-based, dedicated team, and advisory models. The right structure depends on clarity, risk, and the speed of learning required."],
  ["Can you integrate with our current tools?", "Yes. We regularly integrate accounting, payment, CRM, identity, analytics, communication, and industry-specific systems through secure APIs."],
  ["How do you approach AI safely?", "We use permission boundaries, approved data sources, human review where appropriate, monitoring, and transparent evaluation before expanding automation."],
  ["Who owns the source code?", "Our standard client agreements provide full ownership of custom project deliverables after agreed payments are completed."],
  ["Do you provide post-launch support?", "Yes. Support options include monitoring, incident response, maintenance, roadmap delivery, security updates, and team enablement."],
  ["Can you work with our internal technical team?", "Absolutely. We frequently embed alongside internal product, engineering, IT, operations, and security teams."],
  ["How do you protect confidential information?", "We use least-privilege access, encrypted systems, secure development practices, documented controls, and confidentiality agreements."],
  ["Do you design the user experience too?", "Yes. Product strategy, research, information architecture, prototyping, visual design, and usability are integrated into delivery."],
  ["Can you build mobile applications?", "Yes. We develop responsive web apps and native-quality mobile experiences based on your audience, workflows, and device requirements."],
  ["Do you help with cloud migration?", "Yes. We plan and execute migrations with attention to reliability, observability, security, operating cost, and rollback readiness."],
  ["What industries do you know best?", "Our strongest experience spans healthcare, finance, retail, professional services, construction, education, manufacturing, and SaaS."],
  ["How will we track progress?", "You receive a clear roadmap, regular demonstrations, decision logs, delivery metrics, and direct access to the project team."],
  ["Can you rescue a stalled project?", "Yes. We can assess product, code, architecture, and delivery health, then stabilize the most critical risks before rebuilding momentum."],
  ["Do you provide cybersecurity reviews?", "Yes. We review application architecture, identity, permissions, dependencies, data flows, cloud posture, and development practices."],
  ["How can we get an estimate?", "Share your goals through our consultation form. We will clarify scope, recommend an approach, and provide a transparent next-step proposal."],
] as const

export const posts = [
  { slug: "designing-ai-automation", category: "AI", title: "Designing AI automation that earns operational trust", excerpt: "A practical framework for choosing the right tasks, controls, and measures before scaling intelligent automation.", date: "July 8, 2026", read: "7 min read" },
  { slug: "erp-modernization", category: "Transformation", title: "A low-risk path from legacy ERP to connected operations", excerpt: "How phased architecture and workflow redesign create momentum without disrupting the business.", date: "June 24, 2026", read: "9 min read" },
  { slug: "saas-metrics", category: "Product", title: "The SaaS operating metrics that expose real friction", excerpt: "Move beyond surface-level dashboards to understand activation, workflow depth, retention, and value realization.", date: "June 10, 2026", read: "6 min read" },
  { slug: "cloud-cost-control", category: "Cloud", title: "Cloud cost control starts with architecture, not discounts", excerpt: "The engineering decisions that improve unit economics while strengthening reliability and observability.", date: "May 28, 2026", read: "8 min read" },
  { slug: "business-system-discovery", category: "Strategy", title: "What great business-system discovery actually uncovers", excerpt: "A disciplined discovery process reveals hidden handoffs, exceptions, incentives, and opportunities for automation.", date: "May 12, 2026", read: "5 min read" },
  { slug: "secure-api-design", category: "Engineering", title: "Secure API design for connected enterprise products", excerpt: "Build integrations that are resilient, observable, well-governed, and easier for partners to adopt.", date: "April 30, 2026", read: "10 min read" },
] as const

export const stats = [["120+", "products and systems shipped"], ["98%", "client satisfaction"], ["31%", "average workflow acceleration"], ["24/7", "platform monitoring"]] as const

export const navGroups = [
  { label: "Services", href: "/services", items: [["AI Agents", "Intelligent automation for your business."], ["Workflow Automation", "Streamline operations end-to-end."], ["Cloud Infrastructure", "Resilient cloud foundations."], ["Custom Software", "Purpose-built platforms."]] },
  { label: "Solutions", href: "/solutions", items: [["Enterprise", "Scalable solutions for large orgs."], ["Startups", "Move fast with solid foundations."], ["Healthcare", "HIPAA-compliant systems."], ["Finance", "Secure financial platforms."], ["Portfolio", "Selected case studies and projects."]] },
  { label: "Products", href: "/products", items: [["Wolf CRM", "Revenue intelligence platform."], ["Wolf ERP", "Connected operations."], ["Wolf AI", "Secure enterprise AI."]] },
  { label: "Incorporate", href: "/incorporate", items: [["Start Your LLC", "Form your US company today."], ["State Comparison", "Find the best state."], ["Pricing", "Explore packages."]] },
] as const

export const legalContent = {
  privacy: {
    title: "Privacy Policy",
    updated: "July 25, 2026",
    sections: [
      ["1. Introduction", "Wolfitpark LLC (\"Wolfitpark,\" \"we,\" \"our,\" or \"us\") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our services. Please read this policy carefully. By accessing or using our services, you acknowledge that you have read and understood this policy."],
      ["2. Information We Collect", "We collect information you voluntarily provide when you register, fill out forms, submit applications, or communicate with us. This includes: (a) Personal identifiers such as name, email address, phone number, postal address, and date of birth; (b) Business information such as company name, entity type, EIN/SSN, beneficial ownership details, and business address; (c) Payment and financial information such as credit card details, bank account information, and billing addresses (processed directly by our PCI-compliant payment processors — we do not store full card numbers); (d) Identity verification documents such as government-issued IDs and passports; (e) Communication records including emails, chat messages, and support tickets."],
      ["3. Information Collected Automatically", "When you visit our website, we automatically collect: (a) Device and browser information including IP address, browser type, operating system, and device identifiers; (b) Usage data including pages visited, time spent, links clicked, and navigation patterns; (c) Cookies and similar tracking technologies as described in our Cookie Policy."],
      ["4. How We Use Your Information", "We use your information for the following purposes: (a) To provide, process, and manage your service requests and business formation; (b) To communicate with you about your account, services, and support inquiries; (c) To process payments and prevent fraudulent transactions; (d) To comply with legal obligations including anti-money laundering (AML) and Know Your Customer (KYC) requirements; (e) To improve our website, services, and user experience; (f) To send service-related notices, updates, and security alerts; (g) To enforce our terms, policies, and legal agreements."],
      ["5. Lawful Basis for Processing (GDPR)", "If you are located in the European Economic Area (EEA), our lawful bases for processing your personal data include: (a) Performance of a contract — to deliver services you have requested; (b) Legal obligation — to comply with applicable laws and regulations; (c) Legitimate interests — to operate and improve our business; (d) Consent — where you have provided explicit consent for specific processing activities."],
      ["6. Data Sharing and Disclosure", "We do not sell your personal information. We may share your information with: (a) Service providers who assist in business operations — payment processors (Stripe, Coinbase Commerce), identity verification services, cloud infrastructure providers (AWS, Vercel), email and communication services; (b) Government authorities and regulatory bodies as required by law, including state filing offices, IRS, FinCEN, and law enforcement; (c) Professional advisors including attorneys, accountants, and auditors; (d) Business partners with your consent or as necessary to provide services you request. All third-party service providers are contractually obligated to maintain confidentiality and implement appropriate security measures."],
      ["7. PCI DSS Compliance", "Wolfitpark is committed to PCI DSS (Payment Card Industry Data Security Standard) compliance. We do not store, process, or transmit credit card numbers on our servers. All payment transactions are handled by PCI DSS Level 1 certified payment processors. We implement the following security measures: (a) Cardholder data is never stored, logged, or cached on our systems; (b) All payment pages are served over TLS 1.2+ encryption; (c) We use tokenization to replace card data with secure tokens; (d) Regular security scans and penetration testing are conducted; (e) Access to payment systems is restricted on a need-to-know basis; (f) Security policies are reviewed and updated annually."],
      ["8. Data Security", "We implement industry-standard technical, administrative, and physical security measures to protect your information, including: (a) AES-256 encryption for data at rest; (b) TLS 1.2+ encryption for data in transit; (c) Multi-factor authentication for system access; (d) Regular security audits and vulnerability assessments; (e) Employee training on data protection and privacy; (f) Incident response and breach notification procedures."],
      ["9. Data Retention", "We retain your personal information for as long as necessary to fulfill the purposes described in this policy, or as required by applicable law (typically 5-7 years after the end of our business relationship for compliance and legal purposes). When data is no longer needed, it is securely deleted or anonymized."],
      ["10. Your Rights", "Depending on your jurisdiction, you may have the following rights: (a) Right to access — request a copy of your personal data; (b) Right to rectification — correct inaccurate or incomplete data; (c) Right to deletion — request deletion of your data, subject to legal requirements; (d) Right to restrict processing — limit how we use your data; (e) Right to data portability — receive your data in a structured format; (f) Right to object — object to processing based on legitimate interests; (g) Rights under the California Consumer Privacy Act (CCPA) — know, delete, and opt-out of the sale of personal information. To exercise your rights, contact privacy@wolfitpark.online. We will respond within 30 days."],
      ["11. International Data Transfers", "Your information may be transferred to and processed in the United States and other countries where we or our service providers operate. We ensure appropriate safeguards are in place through Standard Contractual Clauses (SCCs) and data processing agreements."],
      ["12. Children's Privacy", "Our services are not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware of such collection, we will delete the information promptly."],
      ["13. Third-Party Links", "Our website may contain links to third-party websites. We are not responsible for the privacy practices or content of these external sites. We encourage you to review their privacy policies before providing any personal information."],
      ["14. Changes to This Policy", "We may update this Privacy Policy from time to time. Material changes will be communicated via email or a prominent notice on our website. Your continued use of our services after changes constitutes acceptance of the updated policy."],
      ["15. Contact Us", "If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us at: Wolfitpark LLC, 701 Amy Cir, Bryant, AR 72022, USA. Email: privacy@wolfitpark.online. Phone: +1 (307) 555-0199."],
    ]
  },
  terms: {
    title: "Terms & Conditions",
    updated: "July 25, 2026",
    sections: [
      ["1. Acceptance of Terms", "By accessing, using, or purchasing any services from Wolfitpark LLC (\"Wolfitpark,\" \"we,\" \"our,\" or \"us\"), you agree to be bound by these Terms & Conditions (\"Terms\"). If you do not agree to all terms, do not use our website or services. These Terms constitute a legally binding agreement between you and Wolfitpark LLC."],
      ["2. Services Description", "Wolfitpark provides business formation services, registered agent services, EIN/ITIN application assistance, BOI/FinCEN filing assistance, compliance monitoring, virtual business address and mail forwarding, software development, AI automation, and related business support services. Service details, scope, and fees are specified in your service agreement or order confirmation."],
      ["3. Eligibility", "By using our services, you represent and warrant that: (a) You are at least 18 years of age; (b) You have the legal capacity to enter into binding contracts; (c) You are not located in a jurisdiction that is subject to US or international sanctions; (d) The information you provide is accurate, complete, and current; (e) You are not using our services for any illegal or unauthorized purpose."],
      ["4. Account Registration", "You must create an account to access certain services. You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account. You agree to notify us immediately of any unauthorized use. We reserve the right to suspend or terminate accounts for security violations or non-compliance."],
      ["5. User Obligations", "You agree to: (a) Provide accurate, current, and complete information; (b) Update your information promptly when changes occur; (c) Use services in compliance with all applicable federal, state, and local laws; (d) Not engage in fraud, misrepresentation, or illegal activities; (e) Not attempt to access, modify, or damage our systems or data; (f) Not use our services to launder money, evade taxes, or conceal beneficial ownership."],
      ["6. Incorporation and Filing Services", "Wolfitpark assists with preparing and filing business formation documents with state authorities. We are not a law firm and do not provide legal advice. State filing fees are separate from our service fees and are paid directly to government agencies. Approval timelines vary by state. We do not guarantee specific processing times or outcomes. You are responsible for reviewing all documents and ensuring accuracy before filing."],
      ["7. Payment Terms", "Fees for services are as specified in your order confirmation or service agreement. Payment is due at the time of order unless otherwise agreed. Accepted payment methods include: credit/debit cards (Visa, Mastercard, American Express, Discover), cryptocurrency (Bitcoin, Ethereum, USDC), and ACH bank transfers. All prices are in US Dollars. We reserve the right to change prices with 30 days notice. Late payments may incur a 1.5% monthly finance charge."],
      ["8. Refund Policy", "Refunds are governed by our Refund Policy, which is incorporated into these Terms by reference. Service fees are eligible for a full refund within 14 days if work has not commenced. State filing fees are non-refundable once submitted. Optional services may be cancelled within 7 days for a full refund if unfulfilled. Custom development projects are governed by the refund terms in your specific contract."],
      ["9. Intellectual Property", "Wolfitpark retains all rights, title, and interest in our proprietary technology, software, tools, templates, and methodologies. Upon full payment, clients receive ownership of custom deliverables specifically created for their project. You may not reproduce, modify, distribute, or reverse-engineer our proprietary materials without written permission."],
      ["10. Confidentiality", "Both parties agree to maintain confidentiality of non-public information shared during the course of business. Confidential information includes business plans, financial data, technical specifications, and customer data. This obligation survives termination of our agreement for 5 years."],
      ["11. Limitation of Liability", "To the maximum extent permitted by applicable law: (a) Wolfitpark's total liability for any claim arising from these Terms or our services is limited to the amount you paid us in the 12 months preceding the claim; (b) We are not liable for indirect, incidental, special, consequential, or punitive damages; (c) We are not liable for damages resulting from government action, regulatory changes, or third-party service failures; (d) We are not liable for delays caused by force majeure events including natural disasters, war, terrorism, or pandemic."],
      ["12. Disclaimer of Warranties", "Our services are provided 'as is' and 'as available' without warranties of any kind, either express or implied. We do not warrant that services will be uninterrupted, error-free, or meet your specific requirements. State filing services are dependent on government processing and we cannot guarantee specific outcomes or timelines."],
      ["13. Indemnification", "You agree to indemnify and hold Wolfitpark, its officers, employees, and agents harmless from any claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising from: (a) Your use of our services; (b) Your violation of these Terms; (c) Your violation of applicable laws; (d) Information you provide that is inaccurate or fraudulent."],
      ["14. Termination", "Either party may terminate agreements as specified in your service contract. We reserve the right to suspend or terminate access to our services immediately if: (a) You breach these Terms; (b) You engage in fraudulent or illegal activity; (c) Required by law or regulatory authority; (d) You fail to pay fees when due. Upon termination, you remain liable for all fees incurred."],
      ["15. Governing Law and Dispute Resolution", "These Terms are governed by the laws of the State of Arkansas, United States, without regard to conflict of law principles. Any disputes shall first be attempted to be resolved through good-faith negotiation. If unresolved, disputes shall be settled by binding arbitration in Saline County, Arkansas, administered by the American Arbitration Association. The prevailing party shall be entitled to reasonable attorney fees."],
      ["16. Entire Agreement", "These Terms, together with our Privacy Policy, Refund Policy, and any service agreements, constitute the entire agreement between you and Wolfitpark regarding your use of our services. They supersede all prior or contemporaneous agreements, communications, and proposals."],
      ["17. Severability", "If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect."],
      ["18. Changes to Terms", "We may modify these Terms at any time. Changes are effective immediately upon posting. We will notify you of material changes via email or website notice. Continued use of services after changes constitutes acceptance."],
      ["19. Contact", "For questions about these Terms, contact: Wolfitpark LLC, 701 Amy Cir, Bryant, AR 72022, USA. Email: legal@wolfitpark.online. Phone: +1 (307) 555-0199."],
    ]
  },
  cookies: {
    title: "Cookie Policy",
    updated: "July 25, 2026",
    sections: [
      ["1. What Are Cookies", "Cookies are small text files stored on your device (computer, tablet, mobile) when you visit a website. They are widely used to make websites work efficiently, enhance user experience, and provide information to website owners. Similar technologies include web beacons, pixel tags, and local storage."],
      ["2. How We Use Cookies", "Wolfitpark LLC uses cookies and similar technologies for the following purposes: (a) Essential/Strictly Necessary — required for website operation, including authentication, security, and session management; (b) Analytics/Performance — to understand how visitors interact with our website, measure traffic, and improve performance; (c) Functional/Preference — to remember your preferences, language, and region settings; (d) Targeting/Advertising — used sparingly to deliver relevant content and measure campaign effectiveness."],
      ["3. Cookies We Use", "Essential cookies: session cookies for login authentication, CSRF tokens for security, load balancing cookies. Analytics cookies: Google Analytics (anonymized IP), Vercel Analytics, PostHog (self-hosted). Functional cookies: theme preference, language selection, recently viewed items. We do not use third-party advertising cookies without your explicit consent."],
      ["4. Third-Party Cookies", "Some cookies are placed by trusted third-party services we use: (a) Vercel — website hosting and analytics; (b) Stripe — payment processing (does not use cookies for tracking); (c) Google Analytics — anonymized usage analytics; (d) Resend — email delivery and analytics. These third parties have their own privacy and cookie policies."],
      ["5. Your Cookie Choices", "When you first visit our website, you are presented with a cookie consent banner that allows you to accept or decline non-essential cookies. You can manage cookies through: (a) Our cookie consent manager (accessible at any time via the Privacy link); (b) Your browser settings (block, delete, or allow cookies); (c) Opt-out tools for specific services (e.g., Google Analytics opt-out). Note that disabling essential cookies may impact website functionality."],
      ["6. Do Not Track Signals", "Our website honors Do Not Track (DNT) signals where supported. When we detect a DNT signal, we limit tracking to essential cookies only."],
      ["7. Data Collected via Cookies", "Cookies may collect: IP address, browser type and version, operating system, referring URL, pages visited, time spent on pages, and click patterns. This data is aggregated and anonymized where possible."],
      ["8. Cookie Retention", "Session cookies expire when you close your browser. Persistent cookies remain on your device for up to 12 months or until manually deleted. You can delete persistent cookies through your browser settings at any time."],
      ["9. Updates to This Policy", "We may update this Cookie Policy. Changes will be posted here with an updated revision date. Material changes will be communicated via cookie consent banner or email."],
      ["10. Contact", "For questions about our use of cookies, contact: Wolfitpark LLC, 701 Amy Cir, Bryant, AR 72022, USA. Email: privacy@wolfitpark.online."],
    ]
  },
  refund: {
    title: "Refund Policy",
    updated: "July 25, 2026",
    sections: [
      ["1. Overview", "Wolfitpark LLC is committed to customer satisfaction. This Refund Policy explains your rights and our obligations regarding refunds for our services. Please review this policy carefully before making a purchase. By purchasing our services, you agree to the terms of this policy."],
      ["2. Service Fees (Formation Packages)", "Our service fees for business formation and filing assistance are refundable according to the following schedule: (a) Full refund within 14 calendar days of purchase if we have not yet filed any documents with the state or commenced work on your order; (b) 50% refund if work has commenced but no state filing has been submitted; (c) No refund after state filing has been submitted. State processing times and outcomes are outside our control."],
      ["3. State Filing Fees", "State filing fees are paid directly to government agencies (Secretary of State, Department of Corporations, etc.) and are non-refundable once submitted. This applies regardless of the application outcome, including rejection or delay. We will inform you of state fees before submission."],
      ["4. Registered Agent Services", "Registered agent service fees are refundable within 14 days of purchase if the service period has not yet begun. Once the service period starts, fees are earned and non-refundable on a pro-rata basis."],
      ["5. Optional Add-On Services", "Optional add-on services including EIN application assistance, BOI filing, mail forwarding, and virtual address: (a) Full refund within 7 days if the service has not been initiated; (b) No refund once the application or service has been submitted to the relevant authority or initiated."],
      ["6. Subscription Services", "Monthly subscription services (compliance monitoring, annual report reminders, etc.): (a) Cancellable at any time; (b) You retain access until the end of your current billing period; (c) No partial refunds for unused portions of a billing period; (d) Annual subscriptions are refundable on a pro-rata basis for the unused portion, minus a 10% processing fee."],
      ["7. Custom Development and Enterprise Services", "Custom software development, enterprise agreements, and consulting services are governed by the refund and cancellation terms specified in your individual service contract or statement of work. These typically include milestone-based payment schedules with refund terms tied to completed deliverables."],
      ["8. Payment Disputes", "If you believe a charge is incorrect, please contact us immediately at billing@wolfitpark.online. We will investigate and respond within 5 business days. Unresolved disputes may be submitted to your financial institution or through binding arbitration as described in our Terms & Conditions."],
      ["9. Refund Processing", "Approved refunds are processed within 5-10 business days. Refunds are credited to your original payment method: (a) Credit/debit card refunds — 5-10 business days to appear on your statement; (b) Cryptocurrency refunds — processed within 24 hours, subject to blockchain network confirmations; (c) ACH/wire refunds — 5-7 business days. Cryptocurrency refunds are denominated in the original cryptocurrency at the exchange rate at the time of refund processing."],
      ["10. Chargeback Policy", "If you initiate a chargeback with your financial institution before contacting us, your account may be immediately suspended. We will provide transaction records to your financial institution to dispute the chargeback. Wrongful chargebacks may result in a $25 administrative fee."],
      ["11. Exceptions", "Exceptions to this Refund Policy may be made at Wolfitpark's sole discretion in extraordinary circumstances. All exceptions must be documented in writing and approved by a Wolfitpark manager."],
      ["12. Governing Law", "This Refund Policy is governed by the laws of the State of Arkansas, United States. Any disputes regarding refunds shall be resolved through the dispute resolution process outlined in our Terms & Conditions."],
      ["13. Contact", "For refund requests or questions, contact: Wolfitpark LLC, 701 Amy Cir, Bryant, AR 72022, USA. Email: billing@wolfitpark.online. Phone: +1 (307) 555-0199."],
    ]
  },
  shipping: {
    title: "Shipping & Delivery Policy",
    updated: "July 25, 2026",
    sections: [
      ["1. Digital Delivery", "Wolfitpark LLC primarily delivers services and documents electronically. Upon successful formation or filing, you will receive: (a) Digital copies of formation documents (Certificate of Formation/Incorporation, Operating Agreement, Bylaws) available for download from your client dashboard; (b) EIN confirmation letter (CP 575) from the IRS via email and dashboard; (c) BOI filing confirmation via email; (d) All communications, invoices, and receipts are delivered electronically. Digital documents are typically available within 1-2 business days after state approval."],
      ["2. Physical Mail Forwarding", "If you subscribe to our Virtual Business Address service with mail forwarding: (a) Physical mail is received at 701 Amy Cir, Bryant, AR 72022; (b) Mail is scanned and uploaded to your dashboard within 1-2 business days of receipt; (c) You may request physical forwarding of mail pieces; (d) Standard forwarding occurs weekly via USPS Priority Mail; (e) Expedited forwarding (next-day) is available for an additional fee; (f) We are not responsible for delays or loss caused by USPS or other carriers."],
      ["3. Shipping Costs", "Mail forwarding shipping costs are included in your virtual address plan for standard (weekly) forwarding within the United States. Expedited shipping and international forwarding are available at additional cost as specified during sign-up or quoted upon request."],
      ["4. Processing Times", "Incorporation document processing depends on the filing state: (a) Expedited states (Delaware, Wyoming, Nevada) — 1-2 business days for state approval; (b) Standard states — 3-10 business days for state approval; (c) Paper filing states — 2-6 weeks for state approval. Processing times are estimates and not guaranteed. State government office closures, holidays, and workload may affect timelines."],
      ["5. International Shipping", "International mail forwarding is available to most countries. Delivery times vary by destination: (a) Canada — 5-10 business days; (b) Europe — 7-14 business days; (c) Asia-Pacific — 10-20 business days; (d) Rest of world — 14-30 business days. Customs duties, taxes, and import fees are the responsibility of the recipient. We are not responsible for items seized or delayed by customs."],
      ["6. Expedited Processing", "Expedited processing options are available for an additional fee: (a) 24-hour expedited state filing (available in select states) — $99; (b) Priority mail forwarding (next-day) — $25 per forwarding; (c) Rush document preparation — $49. Availability varies by state and service type."],
      ["7. Document Replacement", "If you lose or misplace your digital documents, replacement copies are available for download from your dashboard at no charge. Certified copies from the state may require additional fees."],
      ["8. Returned Mail", "If physical mail is returned to us as undeliverable due to an incorrect or outdated address on file, a $10 re-forwarding fee applies. We will attempt to contact you to update your address before disposal."],
      ["9. Abandoned Mail", "Physical mail held at our facility for more than 60 days without forwarding instructions or account renewal may be considered abandoned and disposed of. We will make reasonable efforts to notify you before disposal."],
      ["10. Limitation of Liability", "Wolfitpark is not liable for: (a) Delays caused by government agencies, postal services, or courier companies; (b) Loss of mail by USPS or third-party carriers; (c) Damages resulting from delayed delivery; (d) Customs delays, seizures, or import restrictions for international forwarding."],
      ["11. Contact", "For questions about shipping and delivery, contact: Wolfitpark LLC, 701 Amy Cir, Bryant, AR 72022, USA. Email: support@wolfitpark.online. Phone: +1 (307) 555-0199."],
    ]
  },
  accessibility: {
    title: "Accessibility Statement",
    updated: "July 25, 2026",
    sections: [
      ["1. Commitment", "Wolfitpark LLC is committed to ensuring digital accessibility for all users, including individuals with disabilities. We continuously work to improve the accessibility and usability of our website and services. We believe everyone should be able to access and benefit from our platform regardless of ability."],
      ["2. Standards", "We strive to conform to the Web Content Accessibility Guidelines (WCAG) 2.1 Level AA standards published by the World Wide Web Consortium (W3C). These guidelines outline best practices for making web content accessible to users with various disabilities including visual, auditory, physical, speech, cognitive, and neurological disabilities."],
      ["3. Accessibility Features", "Our website includes the following accessibility features: (a) Keyboard navigation that is logical and consistent; (b) Screen reader compatibility with proper ARIA labels and semantic HTML structure; (c) Sufficient color contrast ratios meeting WCAG AA standards; (d) Resizable text up to 200% without loss of functionality; (e) Alternative text for meaningful images; (f) Descriptive link text — no 'click here' links; (g) Focus indicators for keyboard navigation; (h) Skip navigation links to bypass repeated content; (i) Captions and transcripts for video content where applicable."],
      ["4. Ongoing Efforts", "We employ the following practices to maintain and improve accessibility: (a) Regular automated accessibility audits using industry-standard tools; (b) Periodic manual testing by users with assistive technologies; (c) Accessibility considerations integrated into our design and development workflow; (d) Staff training on inclusive design and accessibility best practices; (e) Third-party accessibility audits conducted annually."],
      ["5. Known Limitations", "We are actively working to address the following known limitations: (a) Some third-party embedded content may not be fully accessible; (b) Some older PDF documents may not be fully screen-reader compatible. If you encounter barriers, please notify us so we can prioritize fixes."],
      ["6. Third-Party Content", "Our website may link to or embed content from third-party platforms. We cannot guarantee the accessibility of third-party content. We encourage third-party providers to maintain accessible practices."],
      ["7. Feedback and Contact", "We welcome feedback on the accessibility of our website and services. If you encounter accessibility barriers, need assistance accessing any content, or wish to report an issue, please contact us: Email: accessibility@wolfitpark.online. Phone: +1 (307) 555-0199. We will make every reasonable effort to provide the information or service in an accessible format."],
      ["8. Accommodation Request", "If you require a reasonable accommodation to access our services, please contact us. We will work with you to identify and provide an appropriate accommodation in a timely manner."],
      ["9. Policy Updates", "We review and update this Accessibility Statement at least annually or when significant changes are made to our website or accessibility practices."],
    ]
  },
} as const

export const processSteps = [["01", "Discover", "Map goals, users, workflows, constraints, and success measures."], ["02", "Design", "Prototype the clearest experience and validate the technical path."], ["03", "Build", "Deliver in visible increments with quality, security, and feedback built in."], ["04", "Scale", "Launch, observe, optimize, and expand what creates measurable value."]] as const

export const iconMap = {
  Activity, RefreshCcw, LockKeyhole, LayoutDashboard, Building2, FileText,
  ClipboardCheck, UserCheck, MapPin, Mail, Receipt, CreditCard, ShoppingCart,
  HeadphonesIcon, MessageSquare, Bell, Key, Globe, Landmark, Settings2,
  ShieldCheck, Star, Users, Bot, Workflow, Code2, Smartphone, PlugZap,
  CloudCog, BarChart3, Palette, Wrench, BriefcaseBusiness, Boxes, Database,
  Store, LineChart, Sparkles, Rocket, GraduationCap, HardHat, ShoppingBag,
  HeartPulse, Cloud,
}

export const stateFees = [
  { state: "Delaware", filingFee: 90, annualReport: 50, franchiseTax: "Min $400", processing: "3-5 days", privacy: "High", rating: 90 },
  { state: "Wyoming", filingFee: 100, annualReport: 60, franchiseTax: "Min $50", processing: "1-2 days", privacy: "Very High", rating: 95 },
  { state: "Nevada", filingFee: 425, annualReport: 150, franchiseTax: "Min $200", processing: "3-5 days", privacy: "High", rating: 80 },
  { state: "Texas", filingFee: 300, annualReport: 0, franchiseTax: "Based on revenue", processing: "5-7 days", privacy: "Medium", rating: 75 },
  { state: "Florida", filingFee: 125, annualReport: 138.75, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 70 },
  { state: "New York", filingFee: 200, annualReport: 9, franchiseTax: "Based on income", processing: "7-10 days", privacy: "Low", rating: 60 },
  { state: "Colorado", filingFee: 50, annualReport: 10, franchiseTax: "None", processing: "3-5 days", privacy: "Medium", rating: 75 },
  { state: "California", filingFee: 70, annualReport: 20, franchiseTax: "Min $800", processing: "5-7 days", privacy: "Low", rating: 55 },
  { state: "Alabama", filingFee: 150, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Alaska", filingFee: 250, annualReport: 100, franchiseTax: "None", processing: "3-5 days", privacy: "High", rating: 70 },
  { state: "Arizona", filingFee: 50, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 70 },
  { state: "Arkansas", filingFee: 45, annualReport: 150, franchiseTax: "None", processing: "7-10 days", privacy: "Low", rating: 55 },
  { state: "Connecticut", filingFee: 120, annualReport: 80, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "District of Columbia", filingFee: 99, annualReport: 0, franchiseTax: "None", processing: "7-10 days", privacy: "Medium", rating: 60 },
  { state: "Georgia", filingFee: 100, annualReport: 50, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Hawaii", filingFee: 50, annualReport: 0, franchiseTax: "None", processing: "7-10 days", privacy: "Medium", rating: 60 },
  { state: "Idaho", filingFee: 100, annualReport: 0, franchiseTax: "None", processing: "3-5 days", privacy: "High", rating: 75 },
  { state: "Illinois", filingFee: 150, annualReport: 75, franchiseTax: "None", processing: "7-10 days", privacy: "Medium", rating: 60 },
  { state: "Indiana", filingFee: 90, annualReport: 0, franchiseTax: "None", processing: "3-5 days", privacy: "Medium", rating: 70 },
  { state: "Iowa", filingFee: 50, annualReport: 45, franchiseTax: "None", processing: "7-10 days", privacy: "Medium", rating: 65 },
  { state: "Kansas", filingFee: 160, annualReport: 50, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Kentucky", filingFee: 40, annualReport: 0, franchiseTax: "None", processing: "7-10 days", privacy: "Low", rating: 55 },
  { state: "Louisiana", filingFee: 100, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Low", rating: 55 },
  { state: "Maine", filingFee: 175, annualReport: 85, franchiseTax: "None", processing: "7-10 days", privacy: "Medium", rating: 60 },
  { state: "Maryland", filingFee: 100, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Massachusetts", filingFee: 500, annualReport: 0, franchiseTax: "None", processing: "7-10 days", privacy: "Low", rating: 50 },
  { state: "Michigan", filingFee: 50, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 70 },
  { state: "Minnesota", filingFee: 135, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Mississippi", filingFee: 50, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 60 },
  { state: "Missouri", filingFee: 50, annualReport: 0, franchiseTax: "None", processing: "3-5 days", privacy: "Medium", rating: 70 },
  { state: "Montana", filingFee: 70, annualReport: 15, franchiseTax: "None", processing: "5-7 days", privacy: "High", rating: 75 },
  { state: "Nebraska", filingFee: 60, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "New Hampshire", filingFee: 100, annualReport: 0, franchiseTax: "None", processing: "3-5 days", privacy: "Medium", rating: 70 },
  { state: "New Jersey", filingFee: 125, annualReport: 50, franchiseTax: "None", processing: "7-10 days", privacy: "Low", rating: 55 },
  { state: "New Mexico", filingFee: 50, annualReport: 0, franchiseTax: "None", processing: "3-5 days", privacy: "High", rating: 80 },
  { state: "North Carolina", filingFee: 125, annualReport: 200, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "North Dakota", filingFee: 135, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 60 },
  { state: "Ohio", filingFee: 99, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Oklahoma", filingFee: 100, annualReport: 25, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Oregon", filingFee: 100, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Pennsylvania", filingFee: 125, annualReport: 0, franchiseTax: "None", processing: "7-10 days", privacy: "Medium", rating: 60 },
  { state: "Rhode Island", filingFee: 150, annualReport: 50, franchiseTax: "None", processing: "7-10 days", privacy: "Low", rating: 55 },
  { state: "South Carolina", filingFee: 110, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "South Dakota", filingFee: 150, annualReport: 0, franchiseTax: "None", processing: "3-5 days", privacy: "High", rating: 80 },
  { state: "Tennessee", filingFee: 300, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Utah", filingFee: 70, annualReport: 0, franchiseTax: "None", processing: "3-5 days", privacy: "Medium", rating: 70 },
  { state: "Vermont", filingFee: 125, annualReport: 0, franchiseTax: "None", processing: "7-10 days", privacy: "Medium", rating: 60 },
  { state: "Virginia", filingFee: 100, annualReport: 0, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
  { state: "Washington", filingFee: 180, annualReport: 60, franchiseTax: "None", processing: "5-7 days", privacy: "Low", rating: 55 },
  { state: "West Virginia", filingFee: 50, annualReport: 0, franchiseTax: "None", processing: "7-10 days", privacy: "Low", rating: 55 },
  { state: "Wisconsin", filingFee: 130, annualReport: 25, franchiseTax: "None", processing: "5-7 days", privacy: "Medium", rating: 65 },
] as const

export const states = [
  { name: "Alabama", code: "AL", region: "South" },
  { name: "Alaska", code: "AK", region: "West" },
  { name: "Arizona", code: "AZ", region: "West" },
  { name: "Arkansas", code: "AR", region: "South" },
  { name: "California", code: "CA", region: "West" },
  { name: "Colorado", code: "CO", region: "West" },
  { name: "Connecticut", code: "CT", region: "Northeast" },
  { name: "Delaware", code: "DE", region: "Northeast" },
  { name: "Florida", code: "FL", region: "South" },
  { name: "Georgia", code: "GA", region: "South" },
  { name: "Hawaii", code: "HI", region: "West" },
  { name: "Idaho", code: "ID", region: "West" },
  { name: "Illinois", code: "IL", region: "Midwest" },
  { name: "Indiana", code: "IN", region: "Midwest" },
  { name: "Iowa", code: "IA", region: "Midwest" },
  { name: "Kansas", code: "KS", region: "Midwest" },
  { name: "Kentucky", code: "KY", region: "South" },
  { name: "Louisiana", code: "LA", region: "South" },
  { name: "Maine", code: "ME", region: "Northeast" },
  { name: "Maryland", code: "MD", region: "Northeast" },
  { name: "Massachusetts", code: "MA", region: "Northeast" },
  { name: "Michigan", code: "MI", region: "Midwest" },
  { name: "Minnesota", code: "MN", region: "Midwest" },
  { name: "Mississippi", code: "MS", region: "South" },
  { name: "Missouri", code: "MO", region: "Midwest" },
  { name: "Montana", code: "MT", region: "West" },
  { name: "Nebraska", code: "NE", region: "Midwest" },
  { name: "Nevada", code: "NV", region: "West" },
  { name: "New Hampshire", code: "NH", region: "Northeast" },
  { name: "New Jersey", code: "NJ", region: "Northeast" },
  { name: "New Mexico", code: "NM", region: "West" },
  { name: "New York", code: "NY", region: "Northeast" },
  { name: "North Carolina", code: "NC", region: "South" },
  { name: "North Dakota", code: "ND", region: "Midwest" },
  { name: "Ohio", code: "OH", region: "Midwest" },
  { name: "Oklahoma", code: "OK", region: "South" },
  { name: "Oregon", code: "OR", region: "West" },
  { name: "Pennsylvania", code: "PA", region: "Northeast" },
  { name: "Rhode Island", code: "RI", region: "Northeast" },
  { name: "South Carolina", code: "SC", region: "South" },
  { name: "South Dakota", code: "SD", region: "Midwest" },
  { name: "Tennessee", code: "TN", region: "South" },
  { name: "Texas", code: "TX", region: "South" },
  { name: "Utah", code: "UT", region: "West" },
  { name: "Vermont", code: "VT", region: "Northeast" },
  { name: "Virginia", code: "VA", region: "South" },
  { name: "Washington", code: "WA", region: "West" },
  { name: "West Virginia", code: "WV", region: "South" },
  { name: "Wisconsin", code: "WI", region: "Midwest" },
  { name: "Wyoming", code: "WY", region: "West" },
] as const

export const teamMembers = [
  { name: "Alex Wolf", role: "CEO & Founder", bio: "Building the future of AI-powered business automation.", image: "" },
  { name: "Sarah Chen", role: "CTO", bio: "20+ years in enterprise software architecture and AI.", image: "" },
  { name: "Marcus Rivera", role: "VP of Engineering", bio: "Leading distributed teams building scalable platforms.", image: "" },
  { name: "Emily Watson", role: "Head of Product", bio: "Product-led growth strategist and UX advocate.", image: "" },
  { name: "David Kim", role: "VP of Sales", bio: "Enterprise sales leader with Fortune 500 experience.", image: "" },
  { name: "Priya Patel", role: "Head of Design", bio: "Crafting premium enterprise experiences.", image: "" },
] as const

export const incorporationFeatures = [
  { title: "LLC Formation", description: "Complete LLC registration in any US state with all required documentation.", icon: "Building2" },
  { title: "Registered Agent", description: "Professional registered agent service to handle legal documents and compliance.", icon: "ShieldCheck" },
  { title: "Virtual Address", description: "Prestigious US business address with mail forwarding and scanning.", icon: "MapPin" },
  { title: "EIN Filing", description: "Federal Employer Identification Number registration with the IRS.", icon: "FileText" },
  { title: "ITIN Assistance", description: "Individual Taxpayer Identification Number application support for international founders.", icon: "Globe" },
  { title: "Compliance", description: "Automated compliance monitoring, annual report filing, and BOI reporting.", icon: "ClipboardCheck" },
] as const

export const registrationSteps = [
  { step: 1, title: "Create Account", description: "Sign up and verify your identity to get started." },
  { step: 2, title: "Business Details", description: "Tell us about your business name, type, and industry." },
  { step: 3, title: "Choose State", description: "Select the best state for your business needs." },
  { step: 4, title: "Registered Agent", description: "Designate a registered agent for legal service of process." },
  { step: 5, title: "Business Address", description: "Choose a virtual or physical business address." },
  { step: 6, title: "Owner Information", description: "Provide details about business owners and ownership structure." },
  { step: 7, title: "EIN Application", description: "Apply for your Federal Employer Identification Number." },
  { step: 8, title: "ITIN (Optional)", description: "Apply for an ITIN if you're an international founder." },
  { step: 9, title: "Compliance", description: "Complete beneficial ownership information reporting." },
  { step: 10, title: "Review & Pay", description: "Review your application and complete payment." },
] as const

export const dashboardNav = [
  { label: "Overview", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "Business Profile", href: "/dashboard/profile", icon: "Building2" },
  { label: "Documents", href: "/dashboard/documents", icon: "FileText" },
  { label: "Formation Status", href: "/dashboard/status", icon: "Activity" },
  { label: "State Filings", href: "/dashboard/filings", icon: "ClipboardCheck" },
  { label: "Compliance", href: "/dashboard/compliance", icon: "ShieldCheck" },
  { label: "Taxes", href: "/dashboard/taxes", icon: "Landmark" },
  { label: "Registered Agent", href: "/dashboard/agent", icon: "UserCheck" },
  { label: "Business Address", href: "/dashboard/address", icon: "MapPin" },
  { label: "Mail", href: "/dashboard/mail", icon: "Mail" },
  { label: "Invoices", href: "/dashboard/invoices", icon: "Receipt" },
  { label: "Payments", href: "/dashboard/payments", icon: "CreditCard" },
  { label: "Orders", href: "/dashboard/orders", icon: "ShoppingCart" },
  { label: "Support", href: "/dashboard/support", icon: "HeadphonesIcon" },
  { label: "Messages", href: "/dashboard/messages", icon: "MessageSquare" },
  { label: "Settings", href: "/dashboard/settings", icon: "Settings2" },
  { label: "Notifications", href: "/dashboard/notifications", icon: "Bell" },
  { label: "API Keys", href: "/dashboard/api-keys", icon: "Key" },
] as const

export const partners = [
  "Stripe", "AWS", "Google Cloud", "Microsoft", "Vercel",
  "Supabase", "Linear", "Notion", "Figma", "Slack",
] as const

export const trustIndicators = [
  { label: "PCI DSS Compliant", description: "Secure payment processing" },
  { label: "SSL 256-bit Encryption", description: "Enterprise-grade security" },
  { label: "SOC 2 Ready", description: "Audited security controls" },
  { label: "99.99% Uptime SLA", description: "Reliable infrastructure" },
  { label: "24/7 Support", description: "Always available" },
  { label: "Enterprise SLA", description: "Guaranteed performance" },
] as const

export const enterpriseStats = [
  ["120+", "Products & Systems Shipped"],
  ["98%", "Client Satisfaction Rate"],
  ["31%", "Average Workflow Acceleration"],
  ["99.99%", "Platform Uptime SLA"],
  ["50+", "Enterprise Clients"],
  ["24/7", "Global Support Coverage"],
] as const

export const servicePackages = [
  {
    id: "mvp",
    title: "Comprehensive MVP Package",
    subtitle: "Complete Cross-Platform Solution",
    description: "Transform your business idea into a complete digital ecosystem. This premium package includes web application, website, iOS app, and Android app development — everything you need to launch across all platforms simultaneously.",
    timeline: "5-6 months",
    stack: ["React Native", "Next.js", "Node.js", "PostgreSQL", "AWS", "TypeScript"],
    features: [
      "Custom web application development",
      "Professional business website",
      "Native iOS application",
      "Native Android application",
      "Unified design system across platforms",
      "Cross-platform data synchronization",
      "Admin dashboard & analytics",
      "User authentication & management",
      "API development & integration",
      "Cloud infrastructure setup",
      "App store deployment assistance",
      "6 months of post-launch support",
    ],
    icon: "Rocket",
  },
  {
    id: "saas",
    title: "SaaS Development",
    subtitle: "Scalable Software-as-a-Service Solutions",
    description: "Build robust, multi-tenant SaaS applications with subscription management, user authentication, and enterprise-grade security. Perfect for businesses looking to create recurring revenue streams.",
    timeline: "8-16 weeks",
    stack: ["Next.js", "React", "Node.js", "PostgreSQL", "Stripe", "Auth0"],
    features: [
      "Multi-tenant architecture design",
      "Stripe payment integration",
      "User management & authentication",
      "Admin dashboards & analytics",
      "API development & documentation",
      "Database optimization",
      "Automated billing & invoicing",
      "Role-based access control",
    ],
    icon: "Cloud",
  },
  {
    id: "ai-automation",
    title: "AI Automation",
    subtitle: "Intelligent Process Automation",
    description: "Leverage artificial intelligence to automate repetitive tasks, analyze data, and enhance user experiences. Transform your business operations with smart automation.",
    timeline: "4-10 weeks",
    stack: ["OpenAI", "Python", "TensorFlow", "Langchain", "Pinecone", "AI SDK"],
    features: [
      "Custom AI model integration",
      "Process automation workflows",
      "Chatbot development",
      "Data analysis & insights",
      "Predictive analytics",
      "Natural language processing",
      "Computer vision solutions",
      "API integrations",
    ],
    icon: "Bot",
  },
  {
    id: "integration",
    title: "System Integration",
    subtitle: "Seamless Third-Party Connections",
    description: "Connect your existing systems and integrate third-party services for streamlined operations. Eliminate data silos and improve workflow efficiency.",
    timeline: "2-8 weeks",
    stack: ["REST APIs", "GraphQL", "Webhooks", "Zapier", "Make.com", "Node.js"],
    features: [
      "API development & integration",
      "Data migration services",
      "Workflow automation",
      "Legacy system modernization",
      "Real-time synchronization",
      "Custom middleware development",
      "Error handling & monitoring",
      "Documentation & training",
    ],
    icon: "PlugZap",
  },
  {
    id: "web-apps",
    title: "Web Applications",
    subtitle: "Modern Responsive Web Solutions",
    description: "Create fast, responsive web applications with modern user interfaces and seamless user experiences. Built with the latest technologies and best practices.",
    timeline: "4-12 weeks",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"],
    features: [
      "Responsive design implementation",
      "Progressive Web App (PWA)",
      "Real-time features",
      "Performance optimization",
      "SEO optimization",
      "Accessibility compliance",
      "Cross-browser compatibility",
      "Mobile-first approach",
    ],
    icon: "Globe",
  },
  {
    id: "custom",
    title: "Custom Solutions",
    subtitle: "Tailored Software Development",
    description: "Get exactly what your business needs with completely custom software solutions. From requirements analysis to ongoing support, we handle every aspect of your project.",
    timeline: "Variable",
    stack: ["Custom stack based on requirements"],
    features: [
      "Requirements analysis & planning",
      "Custom architecture design",
      "Scalable solution development",
      "Quality assurance testing",
      "Deployment & DevOps",
      "Ongoing maintenance & support",
      "Performance monitoring",
      "Feature enhancement",
    ],
    icon: "Settings2",
  },
  {
    id: "formation",
    title: "Business Formation",
    subtitle: "Professional U.S. Business Setup Support",
    description: "Assist with U.S. business formation and compliance so you can launch with confidence and stay aligned with regulatory requirements.",
    timeline: "1-3 weeks",
    stack: ["Entity Formation", "Compliance", "Registered Agent"],
    features: [
      "USA LLC Registration",
      "USA Corporation Registration (C-Corp & S-Corp)",
      "Business Incorporation",
      "Registered Agent Assistance",
    ],
    icon: "Building2",
  },
  {
    id: "tax",
    title: "Tax Services",
    subtitle: "Federal and State Tax Filing Support",
    description: "Support for U.S. and non-U.S. taxpayers with filing needs, EIN applications, and annual report obligations.",
    timeline: "3-7 days",
    stack: ["Tax Compliance", "EIN", "Annual Filings"],
    features: [
      "Federal Tax Filing",
      "State Tax Filing",
      "Resident Tax Filing",
      "Non-Resident Tax Filing",
      "ITIN Assistance",
      "EIN Application",
      "Annual Report Filing",
    ],
    icon: "Landmark",
  },
  {
    id: "banking",
    title: "Banking Support",
    subtitle: "Business Banking and Payment Setup Guidance",
    description: "Help set up business banking relationships and payment infrastructure for smooth company operations.",
    timeline: "2-5 days",
    stack: ["Banking", "FinTech", "Payments"],
    features: [
      "Business Bank Account Assistance",
      "FinTech Banking Setup",
      "Payment Processor Integration",
      "Merchant Account Guidance",
    ],
    icon: "CreditCard",
  },
  {
    id: "compliance",
    title: "Compliance Services",
    subtitle: "Business Compliance and Document Preparation",
    description: "Keep your company organized and compliant with document preparation, BOI filing support, and ongoing business compliance assistance.",
    timeline: "3-10 days",
    stack: ["Compliance", "BOI", "Document Prep"],
    features: [
      "BOI Filing Assistance (where applicable)",
      "Business Compliance",
      "Business Documentation",
      "Operating Agreement Preparation",
    ],
    icon: "ShieldCheck",
  },
  {
    id: "business-support",
    title: "Business Support",
    subtitle: "Business Advisory and Maintenance Support",
    description: "Ongoing advisory support to help maintain, grow, and strengthen your business operations over time.",
    timeline: "Flexible",
    stack: ["Advisory", "Maintenance", "Growth"],
    features: [
      "Business Consultation",
      "Company Maintenance",
      "Virtual Business Address Assistance",
      "Business Growth Advisory",
    ],
    icon: "HeadphonesIcon",
  },
] as const

export const images = {
  hero: [
    "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop",
  ],
  office: [
    "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=2069&auto=format&fit=crop",
  ],
  tech: [
    "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2068&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
  ],
  team: [
    "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=2070&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop",
  ],
  ai: [
    "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1965&auto=format&fit=crop",
  ],
} as const

export const footerLinks = {
  company: [
    { label: "About", href: "/about" },
    { label: "Careers", href: "/careers" },
    { label: "Partners", href: "/partners" },
    { label: "Contact", href: "/contact" },
  ],
  services: [
    { label: "AI Agents", href: "/services/ai-agents" },
    { label: "Workflow Automation", href: "/services/automation" },
    { label: "Cloud Infrastructure", href: "/services/cloud" },
    { label: "Custom Software", href: "/services/software" },
  ],
  solutions: [
    { label: "Enterprise", href: "/solutions/enterprise" },
    { label: "Startups", href: "/solutions/startups" },
    { label: "Healthcare", href: "/solutions/healthcare" },
    { label: "Finance", href: "/solutions/finance" },
  ],
  incorporation: [
    { label: "Start Your Company", href: "/incorporate" },
    { label: "State Comparison", href: "/incorporate/states" },
    { label: "Services", href: "/incorporate/pricing" },
    { label: "Client Dashboard", href: "/dashboard" },
  ],
  resources: [
    { label: "Blog", href: "/blog" },
    { label: "Documentation", href: "/documentation" },
    { label: "API Reference", href: "/api-documentation" },
    { label: "FAQ", href: "/faq" },
  ],
  legal: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms & Conditions", href: "/terms" },
    { label: "Cookie Policy", href: "/cookies" },
    { label: "Refund Policy", href: "/refund" },
    { label: "Shipping Policy", href: "/shipping" },
    { label: "Accessibility", href: "/accessibility" },
  ],
  support: [
    { label: "Help Center", href: "/support" },
    { label: "System Status", href: "/system-status" },
    { label: "Security", href: "/security" },
    { label: "Contact Support", href: "/contact" },
  ],
}
