import type { Metadata } from "next"
import Link from "next/link"
import { ArrowRight, CheckCircle2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { CtaSection, PageHero, SectionHeading } from "@/components/page-sections"
import { solutions } from "@/lib/site-data"
export const metadata:Metadata={title:"Industry Solutions",description:"Digital transformation and business software solutions for startups, healthcare, finance, retail, manufacturing, government, and more.",alternates:{canonical:"/solutions"}}
const outcomes=["Connected operational data","Fewer manual handoffs","Clearer decisions","Secure, scalable delivery"]
export default function SolutionsPage(){return <><PageHero eyebrow="Solutions" title="Context matters. Your system should prove it." description="We combine industry understanding with a fresh view of your workflows, customers, constraints, and opportunity." actions={<Button size="lg" render={<Link href="/consultation"/>}>Discuss your industry<ArrowRight data-icon="inline-end"/></Button>}/><section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Where we help" title="Purpose-built answers for operational complexity."/><div className="mt-12 flex flex-col gap-5">{solutions.map(([title,description,Icon],i)=><article key={title} className="grid gap-6 rounded-2xl border border-border bg-card p-6 transition-colors hover:border-primary/40 md:grid-cols-[.7fr_1.3fr] md:p-8"><div className="flex items-start gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div><span className="text-xs font-semibold text-primary">{String(i+1).padStart(2,"0")}</span><h2 className="mt-2 text-2xl font-semibold">{title}</h2></div></div><div><p className="leading-relaxed text-muted-foreground">{description}</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{outcomes.map(item=><li key={item} className="flex items-center gap-2 text-sm"><CheckCircle2 className="size-4 text-primary"/>{item}</li>)}</ul></div></article>)}</div></div></section><CtaSection title="Your industry has rules. Your future does not need limits." description="Let us design a modern operating model around your real-world requirements."/></>}
