import type { Metadata } from "next"
import Link from "next/link"
import { ArrowRight, BarChart3, MoreHorizontal } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { CtaSection, FeatureList, PageHero, SectionHeading } from "@/components/page-sections"
import { products } from "@/lib/site-data"
export const metadata:Metadata={title:"Wolf Business Products",description:"Explore Wolf CRM, ERP, HR, Inventory, POS, Analytics, AI Assistant, and Workflow products.",alternates:{canonical:"/products"}}
export default function ProductsPage(){return <><PageHero eyebrow="Wolf product suite" title="The operating layer for modern business." description="Modular products that share a common data foundation, thoughtful experience, and intelligence across every workflow." actions={<><Button size="lg" render={<Link href="/consultation"/>}>Request a demo<ArrowRight data-icon="inline-end"/></Button><Button variant="outline" size="lg" render={<Link href="/pricing"/>}>View pricing</Button></>}/><section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Connected by design" title="Start with one workflow. Expand without rebuilding."/><div className="mt-12 grid gap-6 lg:grid-cols-2">{products.map(product=><article key={product.name} className="overflow-hidden rounded-3xl border border-border bg-card"><div className="border-b border-border bg-muted/35 p-4"><div className="overflow-hidden rounded-xl border border-border bg-background"><div className="flex items-center justify-between border-b border-border px-3 py-2"><span className="text-[10px] font-medium">{product.name}</span><MoreHorizontal className="size-3 text-muted-foreground"/></div><div className="grid grid-cols-[.7fr_1.3fr] gap-3 p-3"><div className="rounded-lg bg-foreground p-3 text-background"><product.icon className="size-4 text-primary"/><p className="mt-8 text-2xl font-semibold text-primary">{product.metric}</p><p className="mt-1 text-[9px] text-background/50">{product.metricLabel}</p></div><div className="rounded-lg border border-border p-3"><div className="flex items-center justify-between"><span className="text-[9px] text-muted-foreground">Last 30 days</span><BarChart3 className="size-3 text-primary"/></div><div className="mt-7 flex h-16 items-end gap-1.5">{[42,70,54,83,66,92].map((h,i)=><span key={i} className="flex-1 rounded-t bg-primary" style={{height:`${h}%`,opacity:.35+i*.1}}/>)}</div></div></div></div></div><div className="p-7"><Badge variant="secondary">{product.label}</Badge><h2 className="mt-5 text-2xl font-semibold">{product.name}</h2><p className="mt-3 leading-relaxed text-muted-foreground">{product.description}</p><div className="mt-6"><FeatureList items={product.features}/></div><Button variant="link" className="mt-6 px-0" render={<Link href="/consultation"/>}>Explore {product.name}<ArrowRight data-icon="inline-end"/></Button></div></article>)}</div></div></section><CtaSection title="Build the platform around your business—not the other way around." description="See how the Wolf suite can be configured for your teams, workflows, and growth plan." primary="Request your walkthrough"/></>}
