import Link from "next/link"
import type { Metadata } from "next"
import { ArrowRight, CheckCircle2, ChevronRight, Sparkles, Star, Check, Minus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"
import { FadeIn, FadeInStagger } from "@/components/animation/fade-in"
import { PageTransition } from "@/components/animation/page-transition"
import { SectionWrapper } from "@/components/layout/section-wrapper"
import { incorporationFeatures } from "@/lib/site-data"
import { iconMap } from "@/lib/site-data"

export const metadata: Metadata = {
  title: "Start Your US Company",
  description: "Form your LLC or corporation in any US state. Professional registered agent, EIN filing, ITIN assistance, and compliance support for global founders.",
  alternates: { canonical: "/incorporate" },
}

export default function IncorporatePage() {
  const topStates = [
    { state: "Delaware", filingFee: 90, annualReport: 50, franchiseTax: "Min $400", processing: "3-5 days", privacy: "High" },
    { state: "Wyoming", filingFee: 100, annualReport: 60, franchiseTax: "Min $50", processing: "1-2 days", privacy: "Very High" },
    { state: "Texas", filingFee: 300, annualReport: 0, franchiseTax: "Based on revenue", processing: "5-7 days", privacy: "Medium" },
    { state: "Nevada", filingFee: 425, annualReport: 150, franchiseTax: "Min $200", processing: "3-5 days", privacy: "High" },
    { state: "Florida", filingFee: 125, annualReport: 138.75, franchiseTax: "None", processing: "5-7 days", privacy: "Medium" },
  ]
  const comparison = [
    ["State Filing", true, true, true],
    ["Registered Agent", true, false, true],
    ["EIN Filing", true, false, "Add-on"],
    ["Operating Agreement", true, false, "Add-on"],
    ["Virtual Address", true, false, "Add-on"],
    ["ITIN Assistance", true, false, false],
    ["Compliance Monitoring", true, false, false],
    ["Dedicated Support", true, false, false],
  ] as const
  const steps = [
    ["1", "Choose Your Plan", "Select the right package for your business needs and pick your preferred state."],
    ["2", "Complete Your Profile", "Fill in your business details, owner information, and any optional services."],
    ["3", "We File Everything", "Our team files with the state, obtains your EIN, and delivers your documents."],
  ]
  const faqs = [
    ["How long does incorporation take?", "Processing times vary by state. Most LLCs are processed within 1-7 business days. Expedited options are available for faster processing."],
    ["What's the difference between an LLC and a corporation?", "LLCs offer flexible management and pass-through taxation, while corporations (C-Corp) are better suited for venture capital and public offerings."],
    ["Can international founders incorporate in the US?", "Yes. We help non-US residents form LLCs and corporations in any state. We also provide ITIN assistance and business banking guidance."],
    ["Do I need a registered agent?", "Yes, every US company needs a registered agent. Our Professional and Premium plans include registered agent service for the first year."],
    ["What is a virtual business address?", "A virtual address gives you a prestigious US business address for receiving mail. Mail can be forwarded or scanned to you anywhere."],
    ["What state should I choose?", "The best state depends on your needs. Wyoming and Delaware are popular for privacy and tax benefits. Use our state comparison tool to find the right fit."],
  ]
  const testimonialsData = [
    { quote: "Wolfitpark made incorporating my startup incredibly simple. I had my Wyoming LLC in 2 days. The dashboard keeps everything organized.", name: "Alexandre Dubois", role: "Founder, NovaTech (France)" },
    { quote: "As a non-US resident, I was worried about the complexity. The team handled everything — EIN, ITIN, bank account guidance. Exceptional service.", name: "Yuki Tanaka", role: "CEO, Kira Ventures (Japan)" },
    { quote: "We compared all the major services and Wolfitpark offered the best value. The compliance monitoring alone has saved us from missing annual filings.", name: "Sarah Mitchell", role: "COO, Blueprint Systems" },
  ]
  return <PageTransition>
    <section className="relative overflow-hidden"><div className="hero-grid absolute inset-0 opacity-60"/><div className="absolute inset-x-0 top-0 h-80 bg-primary/5 blur-3xl"/><div className="container-site relative py-20 sm:py-28"><FadeIn><Badge variant="outline" className="mb-6 rounded-full px-3 py-1.5 text-primary"><Sparkles/> Business Incorporation</Badge><h1 className="max-w-4xl text-balance text-5xl font-semibold tracking-[-.055em] sm:text-6xl lg:text-7xl">Start Your US Company<br/><span className="text-gradient">From Anywhere</span></h1><p className="mt-6 max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground">Form your LLC or corporation in any US state. We handle the paperwork, compliance, and filings so you can focus on building your business.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" render={<Link href="/register"/>}>Get Started<ArrowRight data-icon="inline-end"/></Button><Button size="lg" variant="outline" render={<Link href="/incorporate/states"/>}>Compare States</Button></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-primary"/>No hidden fees</span><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-primary"/>100% online</span><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-primary"/>Lifetime support</span></div></FadeIn></div></section>
    <section className="border-y border-border bg-card"><div className="container-site grid grid-cols-2 gap-px py-8 md:grid-cols-4">{([["10,000+","Companies Formed"],["50","US States"],["98%","Satisfaction"],["24h","Avg Processing"]]as const).map(([v,l],i)=><FadeIn key={l} delay={i*0.1}><div className="px-4 py-5 text-center"><p className="text-3xl font-semibold tracking-tight text-gradient">{v}</p><p className="mt-1 text-xs text-muted-foreground">{l}</p></div></FadeIn>)}</div></section>
    <SectionWrapper><div className="container-site"><FadeIn><p className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary"><Sparkles className="size-3.5"/>How It Works</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">Three steps to your US company.</h2><p className="mt-5 max-w-2xl text-pretty text-base leading-relaxed text-muted-foreground sm:text-lg">Complete the entire process online in under 30 minutes. We file everything with the state.</p></FadeIn><FadeInStagger className="mt-12 grid gap-5 md:grid-cols-3">{steps.map(([n,t,d])=><FadeIn key={n}><Card className="relative overflow-hidden border-primary/10 p-6 transition-all hover:border-primary/30 hover:shadow-xl hover:shadow-primary/5"><span className="text-5xl font-bold text-primary/20">{n}</span><h3 className="mt-2 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{d}</p></Card></FadeIn>)}</FadeInStagger></div></SectionWrapper>
    <SectionWrapper className="bg-muted/30"><div className="container-site"><FadeIn><p className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary"><Sparkles className="size-3.5"/>Everything You Need</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">Complete incorporation services.</h2></FadeIn><FadeInStagger className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{incorporationFeatures.map(({title,description,icon})=>{const Ic=iconMap[icon as keyof typeof iconMap];return <FadeIn key={title}><Card className="group cursor-default border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl hover:shadow-primary/5"><div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary">{Ic&&<Ic className="size-5"/>}</div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{description}</p></Card></FadeIn>})}</FadeInStagger></div></SectionWrapper>
    <SectionWrapper><div className="container-site"><FadeIn><p className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary"><Sparkles className="size-3.5"/>Why Wolfitpark</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">The smarter way to incorporate.</h2></FadeIn><div className="mt-12 overflow-x-auto"><table className="w-full min-w-[600px] border-collapse text-left"><thead><tr className="border-b border-border"><th className="py-4 pr-4 text-sm font-semibold">Feature</th><th className="px-4 py-4 text-center text-sm font-semibold text-primary">Wolfitpark</th><th className="px-4 py-4 text-center text-sm text-muted-foreground">DIY</th><th className="px-4 py-4 text-center text-sm text-muted-foreground">Other Services</th></tr></thead><tbody>{comparison.map(([f,w,d,o])=><tr key={f} className="border-b border-border/50"><td className="py-3.5 pr-4 text-sm">{f}</td>{[w,d,o].map((v,i)=><td key={i} className="px-4 py-3.5 text-center text-sm">{v===true?<Check className="mx-auto size-4 text-primary"/>:v===false?<Minus className="mx-auto size-4 text-muted-foreground/40"/>:<span className="text-muted-foreground">{String(v)}</span>}</td>)}</tr>)}</tbody></table></div></div></SectionWrapper>
    <SectionWrapper className="bg-muted/30"><div className="container-site"><FadeIn><p className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary"><Sparkles className="size-3.5"/>Compare States</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">Find the best state for your business.</h2><p className="mt-5 max-w-2xl text-pretty text-base leading-relaxed text-muted-foreground sm:text-lg">Each state has different filing fees, tax requirements, and privacy protections.</p></FadeIn><div className="mt-12 overflow-x-auto"><table className="w-full min-w-[600px] border-collapse text-left"><thead><tr className="border-b border-border"><th className="py-4 pr-4 text-sm font-semibold">State</th><th className="px-4 py-4 text-center text-sm font-semibold">Filing Fee</th><th className="px-4 py-4 text-center text-sm font-semibold">Annual Report</th><th className="px-4 py-4 text-center text-sm font-semibold">Franchise Tax</th><th className="px-4 py-4 text-center text-sm font-semibold">Processing</th><th className="px-4 py-4 text-center text-sm font-semibold">Privacy</th></tr></thead><tbody>{topStates.map(s=><tr key={s.state} className="border-b border-border/50"><td className="py-3.5 pr-4 text-sm font-medium">{s.state}</td><td className="px-4 py-3.5 text-center text-sm">${s.filingFee}</td><td className="px-4 py-3.5 text-center text-sm">{typeof s.annualReport==="number"?`$${s.annualReport}`:s.annualReport}</td><td className="px-4 py-3.5 text-center text-sm">{s.franchiseTax}</td><td className="px-4 py-3.5 text-center text-sm">{s.processing}</td><td className="px-4 py-3.5 text-center text-sm">{s.privacy}</td></tr>)}</tbody></table></div><FadeIn className="mt-8"><Button variant="outline" render={<Link href="/incorporate/states"/>}>View All States<ChevronRight data-icon="inline-end"/></Button></FadeIn></div></SectionWrapper>

    <SectionWrapper className="bg-muted/30"><div className="container-site max-w-3xl"><FadeIn><p className="mb-4 flex items-center justify-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary"><Sparkles className="size-3.5"/>FAQ</p><h2 className="text-balance text-center text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">Common questions.</h2></FadeIn><div className="mt-12 space-y-4">{faqs.map(([q,a],i)=><FadeIn key={i} delay={i*0.05}><Card className="border-border bg-card p-6"><h3 className="text-base font-semibold">{q}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{a}</p></Card></FadeIn>)}</div></div></SectionWrapper>
    <SectionWrapper><div className="container-site"><FadeIn className="text-center"><p className="mb-4 flex items-center justify-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-primary"><Sparkles className="size-3.5"/>Trusted by Founders</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl lg:text-5xl">What our clients say.</h2></FadeIn><FadeInStagger className="mt-12 grid gap-5 lg:grid-cols-3">{testimonialsData.map((t,i)=><FadeIn key={i}><Card className="border-border bg-card p-7"><div className="flex gap-0.5">{Array.from({length:5}).map((_,k)=><Star key={k} className="size-4 fill-primary text-primary"/>)}</div><p className="mt-5 text-sm leading-relaxed">"{t.quote}"</p><div className="mt-6 border-t border-border pt-4"><p className="text-sm font-semibold">{t.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{t.role}</p></div></Card></FadeIn>)}</FadeInStagger></div></SectionWrapper>
    <SectionWrapper><Card className="container-site relative overflow-hidden border-primary/20 bg-primary p-8 text-primary-foreground sm:p-12 lg:flex lg:items-center lg:justify-between lg:p-16"><div className="hero-grid absolute inset-0 opacity-20"/><div className="relative max-w-2xl"><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">Ready to Start Your Company?</h2><p className="mt-4 text-pretty leading-relaxed text-primary-foreground/75">Join 10,000+ founders who have started their US company with Wolfitpark. Begin your registration in under 5 minutes.</p></div><Button variant="secondary" size="lg" className="relative mt-8 lg:mt-0" render={<Link href="/register"/>}>Begin Registration<ArrowRight data-icon="inline-end"/></Button></Card></SectionWrapper>
  </PageTransition>
}
